### ISSUE TITLE
Why don't use dataparallel on i3d?

### ISSUE THREAD

**Issue by ziqi-zhang** [tomrunia/PyTorchConv3D#9]
[Here](https://github.com/tomrunia/PyTorchConv3D/blob/e6cc440e5613d6c826288402c66681a5e6ea5fa0/factory/model_factory.py#L181) you disable dataparallel on i3d and I wonder the reason. Because of it using multi GPUs to train i3d becomes impossible. 

I also tried to modify the code and implement multi GPUs, but I encountered "Runtime Error: Expected tensor for argument 1 'input' to have the same device as tensor for argument 2 'weight'; but device 1 does not equal 0"

**Comment by punknownq** [comment]
If you can understand chinese, refer to this link:https://blog.csdn.net/senius/article/details/96599955 :)

**Comment by ziqi-zhang** [comment]
Ok thanks!
